### ISSUE TITLE
QR code is too small to be scanned

### ISSUE THREAD

**Issue by Krupskis** [eimantas/gpasas-javalin#2]
Tried it at the bar, tried it back at home with [gpasas.lt](https://tikrink.esveikata.lt/)

## Expected behavior
generated QR code is scanned with the [gpasas.lt](https://tikrink.esveikata.lt/) and validation passes.

## Actual behavior
Generated QR code cannot be scanned, because it's too small.

Is there a reason why it is so small? I would love to take a look if I can make it larger.

**Comment by jvitkauskas** [comment]
We don't control QR code size. You can open generated `.pkpass` file as a zip file and review the data.

**Comment by eimantas** [comment]
You can't make the QR code larger as it's [predefined Apple design](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html).

Can you provide the model of your iPhone (or just the screen size). It'd probably make sense to gather user-submitted data on screen sizes vs scannable/un-scannable.

**Comment by Krupskis** [comment]
That’s unfortunate. Iphone 8 plus @eimantas
